package perfectnumber;

import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author GT
 */
public class PerfectNumberInterface extends javax.swing.JFrame {

    /**
     * Creates new form PerfectNumberInterface
     */
    public PerfectNumberInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        val_min = new javax.swing.JTextField();
        val_max = new javax.swing.JTextField();
        calculate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtresult = new javax.swing.JTextArea();
        calculate1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perfect Number");
        setLocationByPlatform(true);
        setResizable(false);

        jLabel1.setText("Enter Minimum Value:");

        jLabel2.setText("Enter Maximum Value:");

        val_min.setText("0");
        val_min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                val_minActionPerformed(evt);
            }
        });
        val_min.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                val_minFocusGained(evt);
            }
        });

        val_max.setText("100");
        val_max.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                val_maxActionPerformed(evt);
            }
        });
        val_max.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                val_maxFocusGained(evt);
            }
        });

        calculate.setText("Generate");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });

        txtresult.setColumns(20);
        txtresult.setRows(5);
        jScrollPane1.setViewportView(txtresult);

        calculate1.setText("Reset");
        calculate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculate1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Instructions: Enter the Minimum Value and the Maximum Value and Click Generate to Generate the Perfect Numbers.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(calculate1)
                                .addGap(18, 18, 18)
                                .addComponent(calculate))
                            .addComponent(val_max)
                            .addComponent(val_min)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(val_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(val_max, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculate)
                    .addComponent(calculate1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void val_minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_val_minActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_val_minActionPerformed

    private void val_maxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_val_maxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_val_maxActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        // TODO add your handling code here:
        int min_val = 0;
        int max_val = 0;
        try{
            min_val = (val_min.getText().toString() == null) ? 0 : Integer.parseInt(val_min.getText());            
        }catch(Exception e){            
            val_min.setBackground(Color.red);
            min_val = -1000000;
        }
        try{
            max_val = (val_max.getText().toString() == null) ? 0 : Integer.parseInt(val_max.getText());                    
        }catch(Exception e){           
            val_max.setBackground(Color.red);
            max_val = -1000000;
        }
        
        if((min_val==-100000)||(max_val==-100000)){
            txtresult.setText("The System only accepts Numbers");
        }else{
            if((min_val<0)||(max_val<=0)){
                txtresult.setText("The System only Allows Positive Numbers between 0 and 1,000,000");
            }else{
                if(min_val>max_val){
                    txtresult.setText("The Miminum Value Entered Cannot be greater than the Maximum Value");
                    val_min.setBackground(Color.red);
                }else{
                    if(min_val==0){min_val+=1;}
                    PerfectNumber perf = new PerfectNumber();
                    String message = "The Perfect Numbers between "+min_val+" and "+max_val+" are: \n";
                    message += perf.getPerfectNumber(min_val, max_val);
                    txtresult.setText(message);
                }

            }
        }
    }//GEN-LAST:event_calculateActionPerformed

    private void calculate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculate1ActionPerformed
        // TODO add your handling code here:
        val_min.setText("0");
        val_max.setText("100");
        txtresult.setText("");
        val_min.setBackground(Color.white);
        val_max.setBackground(Color.white);
    }//GEN-LAST:event_calculate1ActionPerformed

    private void val_minFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_val_minFocusGained
        // TODO add your handling code here:
        val_min.setBackground(Color.white);
        
    }//GEN-LAST:event_val_minFocusGained

    private void val_maxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_val_maxFocusGained
        // TODO add your handling code here:
        val_max.setBackground(Color.white);
    }//GEN-LAST:event_val_maxFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerfectNumberInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerfectNumberInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerfectNumberInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerfectNumberInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerfectNumberInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculate;
    private javax.swing.JButton calculate1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtresult;
    private javax.swing.JTextField val_max;
    private javax.swing.JTextField val_min;
    // End of variables declaration//GEN-END:variables
}
